package com.deepank.careerraft.documents;

import java.io.*;import java.nio.file.*;import java.util.*;import java.util.regex.*;

public class LatexPipeline {
 public void validateStructure(String original,String candidate){for(String p:List.of("\\\\documentclass(?:\\\\[[^\\]]*\\\\])?\\\\{[^}]+\\\\}","\\\\usepackage(?:\\\\[[^\\]]*\\\\])?\\\\{[^}]+\\\\}","\\\\geometry\\\\{[^}]+\\\\}","\\\\begin\\\\{document\\\\}","\\\\end\\\\{document\\\\}"))if(!Pattern.compile(p,Pattern.DOTALL).matcher(original).results().map(MatchResult::group).toList().equals(Pattern.compile(p,Pattern.DOTALL).matcher(candidate).results().map(MatchResult::group).toList()))throw new IllegalArgumentException("Protected LaTeX structure changed: "+p);}
 public String replacePlaceholders(String template,Map<String,String>replacements){Set<String>allowed=Set.of("NAME","CONTACT","SKILLS","EDUCATION","CERTIFICATES");if(!allowed.containsAll(replacements.keySet()))throw new IllegalArgumentException("Attempted mutation of unapproved placeholders");String out=template;for(var e:replacements.entrySet()){String t="{{"+e.getKey()+"}}";if(!out.contains(t))throw new IllegalArgumentException("Required placeholder not found: "+e.getKey());out=out.replaceFirst(Pattern.quote(t),Matcher.quoteReplacement(e.getValue()));}return out;}
 public String render(String template,Map<String,String>regions){String out=template;for(var e:regions.entrySet()){if(!Set.of("EXPERIENCE_BULLETS","PROJECTS").contains(e.getKey()))throw new IllegalArgumentException("Attempted mutation of unapproved region: "+e.getKey());String start="% === "+e.getKey()+"_START ===",end="% === "+e.getKey()+"_END ===";String pattern=Pattern.quote(start)+".*?"+Pattern.quote(end);String replacement=start+"\n"+e.getValue()+"\n"+end;out=out.replaceFirst("(?s)"+pattern,Matcher.quoteReplacement(replacement));if(out.equals(template)&&!template.contains(start))throw new IllegalArgumentException("Required mutable block not found: "+e.getKey());}validateStructure(template,out);return out;}
 public Path compile(Path tex)throws Exception{if(!commandExists("latexmk"))throw new IllegalStateException("latexmk is required");Process p=new ProcessBuilder("latexmk","-pdf","-interaction=nonstopmode","-halt-on-error",tex.getFileName().toString()).directory(tex.getParent().toFile()).redirectErrorStream(true).start();String logs=new String(p.getInputStream().readAllBytes());if(p.waitFor()!=0)throw new IllegalStateException("LaTeX compilation failed:\n"+logs.substring(Math.max(0,logs.length()-6000)));Path pdf=tex.resolveSibling(tex.getFileName().toString().replaceFirst("\\.tex$",".pdf"));if(!Files.exists(pdf))throw new FileNotFoundException(pdf.toString());return pdf;}
 public void validatePageCount(Path pdf)throws Exception{if(!commandExists("pdfinfo"))return;Process p=new ProcessBuilder("pdfinfo",pdf.toString()).redirectErrorStream(true).start();String s=new String(p.getInputStream().readAllBytes());p.waitFor();Matcher m=Pattern.compile("Pages:\\s+(\\d+)").matcher(s);if(m.find()&&Integer.parseInt(m.group(1))>1)throw new IllegalArgumentException("Resume exceeds 1 page");}
 private boolean commandExists(String name){try{Process p=new ProcessBuilder("sh","-c","command -v "+name).start();return p.waitFor()==0;}catch(Exception e){return false;}}
}
