package com.deepank.careerraft.discovery;

import com.fasterxml.jackson.databind.*;import com.deepank.careerraft.domain.Job;import org.springframework.stereotype.Component;import java.net.URLEncoder;import java.nio.charset.StandardCharsets;import java.time.Instant;import java.util.*;

@Component public class GoogleCareersJobSource implements JobSource{
 private final SimpleHttpClient http;private final ObjectMapper mapper=new ObjectMapper();public GoogleCareersJobSource(SimpleHttpClient h){http=h;}public String provider(){return "google_careers";}
 public List<Job>fetch(SourceDefinition d){String q=Objects.toString(d.options().getOrDefault("query","software engineer"));List<String>locs=stringList(d.options().getOrDefault("locations",List.of("India")));int pages=num(d.options().getOrDefault("max_pages",2)),max=num(d.options().getOrDefault("max_jobs",40));List<Job>out=new ArrayList<>();for(int page=1;page<=Math.max(1,pages)&&out.size()<max;page++){List<Job>b=fetchPage(d.name(),q,locs,page);out.addAll(b);if(b.size()<20)break;}return out.stream().limit(max).toList();}
 private List<Job>fetchPage(String source,String q,List<String>locs,int page){List<Object>slots=new ArrayList<>(Collections.nCopies(17,null));slots.set(0,q.isBlank()?null:q);slots.set(4,"en-US");slots.set(6,locs.stream().map(List::of).toList());slots.set(7,page);try{String inner=mapper.writeValueAsString(List.of(slots)),req=mapper.writeValueAsString(List.of(List.of("r06xKb",inner,null,"generic")));var r=http.postForm("https://www.google.com/about/careers/applications/_/HiringCportalFrontendUi/data/batchexecute","f.req="+URLEncoder.encode(req,StandardCharsets.UTF_8));JsonNode payload=decode(r.body());if(payload==null||!payload.isArray()||payload.isEmpty())return List.of();JsonNode jobs=payload.get(0);List<Job>out=new ArrayList<>();if(jobs!=null&&jobs.isArray())for(JsonNode rec:jobs)if(rec.isArray()){Job j=toJob(source,rec);if(j!=null)out.add(j);}return out;}catch(Exception e){throw new IllegalStateException("Unable to parse Google Careers response",e);}}
 private JsonNode decode(String raw){for(String line:(raw==null?"":raw).split("\\R")){String s=line.trim();if(!s.startsWith("[[\\\"wrb.fr\\\""))continue;try{JsonNode env=mapper.readTree(s);JsonNode p=env.path(0).path(2);return p.isMissingNode()||p.asText().isBlank()?null:mapper.readTree(p.asText());}catch(Exception ignored){}}return null;}
 private Job toJob(String source,JsonNode r){String id=r.size()>0?r.get(0).asText(""):"",title=r.size()>1?r.get(1).asText(""):"";String desc=body(r,10),qual=body(r,4),resp=body(r,3),min=body(r,19);String combined=String.join("\n\n",new LinkedHashSet<>(List.of(desc,min,qual,resp)).stream().filter(s->!s.isBlank()).toList());if(id.isBlank()||title.isBlank()||combined.length()<100)return null;List<String>locations=new ArrayList<>();if(r.size()>9&&r.get(9).isArray())for(JsonNode e:r.get(9))if(e.isArray()&&!e.isEmpty())locations.add(e.get(0).asText());Instant posted=timestamp(r,12);return new Job(SourceSupport.jobId(source,id),source,id,r.size()>7?r.get(7).asText("Google"):"Google",title,"https://www.google.com/about/careers/applications/jobs/results/"+id,combined,String.join("; ",new LinkedHashSet<>(locations)),null,null,null,posted,null);}
 private String body(JsonNode r,int i){if(i>=r.size())return "";JsonNode n=r.get(i);return n.isArray()&&n.size()>1?org.jsoup.Jsoup.parse(n.get(1).asText("")).text():org.jsoup.Jsoup.parse(n.asText("")).text();}private Instant timestamp(JsonNode r,int i){try{return i<r.size()?Instant.ofEpochSecond(r.get(i).get(0).asLong()):null;}catch(Exception e){return null;}}private static int num(Object o){return Integer.parseInt(String.valueOf(o));}private static List<String>stringList(Object o){if(o instanceof List<?>l)return l.stream().map(String::valueOf).toList();return List.of(String.valueOf(o));}
}
