package com.deepank.careerraft.career;

import com.fasterxml.jackson.databind.*;import com.deepank.careerraft.discovery.SimpleHttpClient;import org.springframework.stereotype.Service;import java.util.*;

@Service public class RepositoryMiningService{
 private final SimpleHttpClient http;private final ObjectMapper mapper=new ObjectMapper();private static final Set<String>INTERESTING=Set.of("README.md","README","pom.xml","build.gradle","build.gradle.kts","package.json","requirements.txt","pyproject.toml","Dockerfile","docker-compose.yml","docker-compose.yaml",".gitlab-ci.yml");
 public RepositoryMiningService(SimpleHttpClient h){http=h;}
 public RepositoryObservation mine(String repository,String provider,String token){try{return "github".equalsIgnoreCase(provider)?mineGithub(repository,token):"gitlab".equalsIgnoreCase(provider)?mineGitlab(repository,token):throwUnsupported(provider);}catch(Exception e){throw new IllegalStateException("Repository mining failed for "+repository,e);}}
 private RepositoryObservation mineGithub(String repository,String token)throws Exception{String[]parts=repository.split("/",2);Map<String,Object>repo=get("https://api.github.com/repos/"+repository,token);String branch=String.valueOf(repo.get("default_branch"));Map<String,Object>tree=get("https://api.github.com/repos/"+repository+"/git/trees/"+enc(branch)+"?recursive=1",token);List<Map<String,String>>files=new ArrayList<>();Object raw=tree.get("tree");if(raw instanceof List<?>l)for(Object o:l)if(o instanceof Map<?,?>m&&"blob".equals(String.valueOf(m.get("type")))){String path=String.valueOf(m.get("path"));if(interesting(path)){try{Map<String,Object>payload=get("https://api.github.com/repos/"+repository+"/contents/"+path.replace(" ","%20")+"?ref="+enc(branch),token);String b64=String.valueOf(payload.get("content")).replaceAll("\\s","");String content=new String(Base64.getDecoder().decode(b64),java.nio.charset.StandardCharsets.UTF_8);files.add(Map.of("path",path,"content",content.substring(0,Math.min(100000,content.length()))));}catch(Exception ignored){files.add(Map.of("path",path,"content",""));}}}return observation(repository,"github",branch,files,"https://github.com/"+repository);}
 private RepositoryObservation mineGitlab(String repository,String token)throws Exception{String project=enc(repository);String base="https://gitlab.com/api/v4/projects/"+project;Map<String,Object>repo=get(base,token);String branch=String.valueOf(repo.get("default_branch"));var arr=http.get(base+"/repository/tree?ref="+enc(branch)+"&recursive=true&per_page=100","application/json",gitlabHeaders(token)).body();JsonNode n=mapper.readTree(arr);List<Map<String,String>>files=new ArrayList<>();if(n.isArray())for(JsonNode x:n)if("blob".equals(x.path("type").asText())){String path=x.path("path").asText();if(interesting(path)){try{Map<String,Object>p=mapper.readValue(http.get(base+"/repository/files/"+enc(path)+"?ref="+enc(branch),"application/json",gitlabHeaders(token)).body(),Map.class);String b64=String.valueOf(p.get("content")).replaceAll("\\s","");String c=new String(Base64.getDecoder().decode(b64),java.nio.charset.StandardCharsets.UTF_8);files.add(Map.of("path",path,"content",c.substring(0,Math.min(100000,c.length()))));}catch(Exception ignored){files.add(Map.of("path",path,"content",""));}}}return observation(repository,"gitlab",branch,files,"https://gitlab.com/"+repository);}
 private RepositoryObservation observation(String repo,String provider,String branch,List<Map<String,String>>files,String url){String text=files.stream().map(x->x.get("path")+"\n"+x.get("content")).reduce("",String::concat).toLowerCase(Locale.ROOT);Map<String,List<String>>patterns=Map.ofEntries(Map.entry("Java",List.of("pom.xml","build.gradle","java")),Map.entry("Spring Boot",List.of("spring-boot","spring boot")),Map.entry("Python",List.of("requirements.txt","pyproject.toml","python")),Map.entry("JavaScript",List.of("package.json","javascript","node")),Map.entry("React",List.of("react")),Map.entry("TypeScript",List.of("typescript",".tsx",".ts")),Map.entry("Redis",List.of("redis")),Map.entry("Lua",List.of("lua")),Map.entry("Kubernetes",List.of("kubernetes","k8s","deployment.yaml")),Map.entry("Docker",List.of("dockerfile","docker")),Map.entry("CI/CD",List.of(".gitlab-ci.yml",".github/workflows","pipeline")),Map.entry("AWS",List.of("aws","ecr","aurora","s3","ec2")),Map.entry("PostgreSQL",List.of("postgres")),Map.entry("MySQL",List.of("mysql")),Map.entry("MongoDB",List.of("mongodb")),Map.entry("Kafka",List.of("kafka")),Map.entry("gRPC",List.of("grpc")),Map.entry("Solidity",List.of("solidity",".sol")),Map.entry("MetaMask",List.of("metamask")),Map.entry("NumPy",List.of("numpy")),Map.entry("Pandas",List.of("pandas")),Map.entry("Scikit-learn",List.of("scikit-learn","sklearn")),Map.entry("Matplotlib",List.of("matplotlib")));List<String>tech=patterns.entrySet().stream().filter(e->e.getValue().stream().anyMatch(text::contains)).map(Map.Entry::getKey).toList();List<String>signals=new ArrayList<>();if(files.stream().anyMatch(x->x.get("path").endsWith("Dockerfile")))signals.add("dockerfile_present");if(files.stream().anyMatch(x->x.get("path").startsWith(".github/workflows/")||x.get("path").equals(".gitlab-ci.yml")))signals.add("ci_configuration_present");if(files.stream().anyMatch(x->x.get("path").startsWith("k8s/")||x.get("path").startsWith("kubernetes/")))signals.add("kubernetes_configuration_present");if(files.stream().anyMatch(x->x.get("path").equals("README.md")||x.get("path").endsWith("/README.md")))signals.add("readme_present");return new RepositoryObservation(repo,provider,branch,files.stream().map(x->x.get("path")).toList(),tech,signals,url);}
 private Map<String,Object> get(String url,String token)throws Exception{
     Map<String,String> headers=new LinkedHashMap<>();
     if(token!=null&&!token.isBlank()) headers.put("Authorization","Bearer "+token);
     Map<String,Object> m=mapper.readValue(
             http.get(url,"application/json",headers).body(),Map.class);
     return m;
 }private boolean interesting(String p){String b=p.substring(p.lastIndexOf('/')+1);return INTERESTING.contains(b)||p.startsWith(".github/workflows/")||p.startsWith(".gitlab/")||p.startsWith("k8s/")||p.startsWith("kubernetes/");}private static String enc(String s){return java.net.URLEncoder.encode(s,java.nio.charset.StandardCharsets.UTF_8);}
 private Map<String,String> gitlabHeaders(String token){Map<String,String> h=new LinkedHashMap<>();if(token!=null&&!token.isBlank())h.put("PRIVATE-TOKEN",token);return h;}
 private RepositoryObservation throwUnsupported(String p){throw new IllegalArgumentException("Unsupported repository provider: "+p);}
}
